# .github/workflows/norm.yml
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Norminette
        run: |
          docker build -t norminette .
          docker run -v $PWD:/code norminette /code